[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
comment-token = "#"
language-servers = [ "nil" ]
indent = { tab-width = 2, unit = "  " }
formatter = {command = "nixfmt"}

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "biome"]

[language-server.vale]
command = "vale-ls"

[[language]]
name = "markdown"
language-servers = ["vale", "marksman"]

[language-server.hyprls]
command = "hyprls"

[[language]]
name = "hyprlang"
scope = "source.hyprlang"
roots = ["hyprland.conf"]
file-types = [ { glob = "hyprland.conf" }, { glob = "hyprpaper.conf" }, { glob = "hypridle.conf" }, { glob = "hyprlock.conf" }, { glob = "jake.conf" }, { glob = "iberu.conf" } ]
comment-token = "#"
grammar = "hyprlang"
language-servers = [ "hyprls" ]
