vim.o.termguicolors = true
vim.o.termguicolors = true
vim.o.showmode = false
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.autochdir = true
vim.o.conceallevel = 2
vim.o.cmdheight = 2
vim.o.cursorline = false
vim.o.number =true;
